print("hello world")
print("Maryam")
print("first name:Maryam , last name:Shahzadi")
print("1 2 3")
print("Hello \n World")
print("Hello \t World")
print("'apple ,banana ,cherry'")
print("'1-2-3'")
print("'Hello \t World'")
print("'12'")
print('"Hello!"')
print("this is backslash:\\")
print("I am 21 years old")
print("The number is 5")
print("1")
print("2")
print("3")
print("4")
print("5")